# This is the production variant of
# docker deployment for basic-crud
version: '3'
services:

  # development instance
  app-development:
    image: index.docker.io/{{docker_account}}/basic-crud:development
    container_name: 'app-development'
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - MONGO_HOST=database
      - MONGO_DB=basic-crud-development
      - HOST=http://{{aws_development}}/development/api/
    env_file:
      - .env

  app-admin:
    image: index.docker.io/{{docker_account}}/basic-crud:development
    container_name: 'app-admin'
    ports:
      - 8001:8001
    environment:
      - NODE_ENV=development
      - URL=http://{{aws_development}}/development/api/


  # nginx for port forwarding and proxy server
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    depends_on:
      - app-development
    ports:
      - "80:80"
    volumes:
      - ./configurations/nginx-development.conf:/etc/nginx/conf.d/default.conf
      # - ./certs:/etc/nginx/certs

  watchtower:
    image: v2tec/watchtower
    container_name: 'watchtower'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/config.json:/config.json
    command: --interval 10 --cleanup
