# This is the production variant of
# docker deployment for {{app_name}}
version: '3'
services:

  # development instance
  app:
    image: index.docker.io/{{docker_account}}/{{app_name}}:development
    container_name: 'app'
    ports:
      - 3000:3000
    links:
      - database
    depends_on:
      - database
    environment:
      - NODE_ENV=production
      - MONGO_HOST=database
      - MONGO_DB={{app_name}}
    env_file:
      - .env

  # nginx for port forwarding and proxy server
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./configurations/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./certs:/etc/nginx/certs

  watchtower:
    image: v2tec/watchtower
    container_name: 'watchtower'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/config.json:/config.json
    command: --interval 10 --cleanup
